on: 
    push:
        branches: [master]
    

jobs:
    build:
        runs-on: manu
        
        steps:
          
            
            - uses: actions/checkout@v4
            
            - name: Log in to Docker Hub
              run: |
                echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
                docker image build -t manu100/manu:tagname .
                docker push manu100/manu:tagname
